### PR TITLE
Fastqc

### PR DESCRIPTION
**Pull request by JihedC**
Add rule fastqc to the snakemake pipeline
Generates **.zip** and **.html** file for the fastq after trimming.

### CODE REVIEW

**Comment by JihedC** [comment]
I have added wget in the environnement file because on my local computer it asked for it

**Comment by JihedC** [comment]
I spotted 1 mistake I made, the shell command doesn't output the log of the QC to the folder/files created by snakemake.
This is because I remove the `2> {log}` at the end of the shell directive.

**Comment by mgalland** [comment]
Everything works except on genseq for some obscure reason (java configuration). An improvement for later is to use singularity with a docker image. 
By writing in a Snakefile: `singularity: "docker://continuumio/miniconda3:4.4.10"` for instance.
See here for more info: https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#combining-conda-package-management-with-containers

**Comment by JihedC** [comment]
Thanks, then I will merge it !

**Pull request merged**
